using System.Text.Json.Serialization;

namespace CSPlotlySlim.Chart.Generic.Properties;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Symbol
{
    [JsonStringEnumMemberName("circle")]
    Circle,
    [JsonStringEnumMemberName("circle-open")]
    CircleOpen,
    [JsonStringEnumMemberName("circle-dot")]
    CircleDot,
    [JsonStringEnumMemberName("circle-open-dot")]
    CirleOpenDot,
    [JsonStringEnumMemberName("square")]
    Square,
    [JsonStringEnumMemberName("square-open")]
    SquareOpen,
    [JsonStringEnumMemberName("square-dot")]
    SquareDot,
    [JsonStringEnumMemberName("square-open-dot")]
    SquareOpenDot,
    [JsonStringEnumMemberName("diamond")]
    Diamond,
    [JsonStringEnumMemberName("diamond-open")]
    DiamondOpen,
    [JsonStringEnumMemberName("diamond-dot")]
    DiamondDot,
    [JsonStringEnumMemberName("diamond-open-dot")]
    DiamondOpenDot,
    [JsonStringEnumMemberName("cross")]
    Cross,
    [JsonStringEnumMemberName("cross-open")]
    CrossOpen,
    [JsonStringEnumMemberName("cross-dot")]
    CrossDot,
    [JsonStringEnumMemberName("cross-open-dot")]
    CrossOpenDot,
    [JsonStringEnumMemberName("x")]
    X,
    [JsonStringEnumMemberName("x-open")]
    XOpen,
    [JsonStringEnumMemberName("x-dot")]
    XDot,
    [JsonStringEnumMemberName("x-open-dot")]
    XOpenDot,
    [JsonStringEnumMemberName("triangle-up")]
    TriangleUp,
    [JsonStringEnumMemberName("triangle-up-open")]
    TriangleUpOpen,
    [JsonStringEnumMemberName("triangle-up-dot")]
    TriangleUpDot,
    [JsonStringEnumMemberName("triangle-up-open-dot")]
    TriangleUpOpenDot,
    [JsonStringEnumMemberName("triangle-down")]
    TriangleDown,
    [JsonStringEnumMemberName("triangle-down-open")]
    TriangleDownOpen,
    [JsonStringEnumMemberName("triangle-down-dot")]
    TriangleDownDot,
    [JsonStringEnumMemberName("triangle-down-open-dot")]
    TriangleDownOpenDot,
    [JsonStringEnumMemberName("triangle-left")]
    TriangleLeft,
    [JsonStringEnumMemberName("triangle-left-open")]
    TriangleLeftOpen,
    [JsonStringEnumMemberName("triangle-left-dot")]
    TriangleLeftDot,
    [JsonStringEnumMemberName("triangle-left-open-dot")]
    TriangleLeftOpenDot,
    [JsonStringEnumMemberName("triangle-right")]
    TriangleRight,
    [JsonStringEnumMemberName("triangle-right-open")]
    TriangleRightOpen,
    [JsonStringEnumMemberName("triangle-right-dot")]
    TriangleRightDot,
    [JsonStringEnumMemberName("triangle-right-open-dot")]
    TriangleRightOpenDot,
    [JsonStringEnumMemberName("triangle-northeast")]
    TriangleNorthEast,
    [JsonStringEnumMemberName("triangle-northeast-open")]
    TriangleNorthEastOpen,
    [JsonStringEnumMemberName("triangle-northeast-dot")]
    TriangleNorthEastDot,
    [JsonStringEnumMemberName("triangle-northeast-open-dot")]
    TriangleNorthEastOpenDot,
    [JsonStringEnumMemberName("triangle-southeast")]
    TriangleSouthEast,
    [JsonStringEnumMemberName("triangle-southeast-open")]
    TriangleSouthEastOpen,
    [JsonStringEnumMemberName("triangle-southeast-dot")]
    TriangleSouthEastDot,
    [JsonStringEnumMemberName("triangle-southeast-open-dot")]
    TriangleSouthEastOpenDot,
    [JsonStringEnumMemberName("triangle-southwest")]
    TriangleSouthWest,
    [JsonStringEnumMemberName("triangle-southwest-open")]
    TriangleSouthWestOpen,
    [JsonStringEnumMemberName("triangle-southwest-dot")]
    TriangleSouthWestDot,
    [JsonStringEnumMemberName("triangle-southwest-open-dot")]
    TriangleSouthWestOpenDot,
    [JsonStringEnumMemberName("triangle-northwest")]
    TriangleNorthWest,
    [JsonStringEnumMemberName("triangle-northwest-open")]
    TriangleNorthWestOpen,
    [JsonStringEnumMemberName("triangle-northwest-dot")]
    TriangleNorthWestDot,
    [JsonStringEnumMemberName("triangle-northwest-open-dot")]
    TriangleNorthWestOpenDot,
    [JsonStringEnumMemberName("pentagon")]
    Pentagon,
    [JsonStringEnumMemberName("pentagon-open")]
    PentagonOpen,
    [JsonStringEnumMemberName("pentagon-dot")]
    PentagonDot,
    [JsonStringEnumMemberName("pentagon-open-dot")]
    PentagonOpenDot,
    [JsonStringEnumMemberName("hexagon")]
    Hexagon,
    [JsonStringEnumMemberName("hexagon-open")]
    HexagonOpen,
    [JsonStringEnumMemberName("hexagon-dot")]
    HexagonDot,
    [JsonStringEnumMemberName("hexagon-open-dot")]
    HexagonOpenDot,
    [JsonStringEnumMemberName("hexagon2")]
    Hexagon2,
    [JsonStringEnumMemberName("hexagon2-open")]
    Hexagon2Open,
    [JsonStringEnumMemberName("hexagon2-dot")]
    Hexagon2Dot,
    [JsonStringEnumMemberName("hexagon2-open-dot")]
    Hexagon2OpenDot,
    [JsonStringEnumMemberName("octagon")]
    Octagon,
    [JsonStringEnumMemberName("octagon-open")]
    OctagonOpen,
    [JsonStringEnumMemberName("octagon-dot")]
    OctagonDot,
    [JsonStringEnumMemberName("octagon-open-dot")]
    OctagonOpenDot,
    [JsonStringEnumMemberName("star")]
    Star,
    [JsonStringEnumMemberName("star-open")]
    StarOpen,
    [JsonStringEnumMemberName("star-dot")]
    StarDot,
    [JsonStringEnumMemberName("star-open-dot")]
    StarOpenDot,
    [JsonStringEnumMemberName("hexagram")]
    Hexagram,
    [JsonStringEnumMemberName("hexagram-open")]
    HexagramOpen,
    [JsonStringEnumMemberName("hexagram-dot")]
    HexagramDot,
    [JsonStringEnumMemberName("hexagram-open-dot")]
    HexagramOpenDot,
    [JsonStringEnumMemberName("star-triangle-up")]
    StarTriangleUp,
    [JsonStringEnumMemberName("star-triangle-up-open")]
    StarTriangleUpOpen,
    [JsonStringEnumMemberName("star-triangle-up-dot")]
    StarTriangleUpDot,
    [JsonStringEnumMemberName("star-triangle-up-open-dot")]
    StarTriangleUpOpenDot,
    [JsonStringEnumMemberName("star-triangle-down")]
    StarTriangleDown,
    [JsonStringEnumMemberName("star-triangle-down-open")]
    StarTriangleDownOpen,
    [JsonStringEnumMemberName("star-triangle-down-dot")]
    StarTriangleDownDot,
    [JsonStringEnumMemberName("star-triangle-down-open-dot")]
    StarTriangleDownOpenDot,
    [JsonStringEnumMemberName("star-square")]
    StarSquare,
    [JsonStringEnumMemberName("star-square-open")]
    StarSquareOpen,
    [JsonStringEnumMemberName("star-square-dot")]
    StarSquareDot,
    [JsonStringEnumMemberName("star-square-open-dot")]
    StarSquareOpenDot,
    [JsonStringEnumMemberName("star-diamond")]
    StarDiamond,
    [JsonStringEnumMemberName("star-diamond-open")]
    StarDiamondOpen,
    [JsonStringEnumMemberName("star-diamond-dot")]
    StarDiamondDot,
    [JsonStringEnumMemberName("star-diamond-open-dot")]
    StarDiamondOpenDot,
    [JsonStringEnumMemberName("diamond-tall")]
    DiamondTall,
    [JsonStringEnumMemberName("diamond-tall-open")]
    DiamondTallOpen,
    [JsonStringEnumMemberName("diamond-tall-dot")]
    DiamondTallDot,
    [JsonStringEnumMemberName("diamond-tall-open-dot")]
    DiamondTallOpenDot,
    [JsonStringEnumMemberName("diamond-wide")]
    DiamondWide,
    [JsonStringEnumMemberName("diamond-wide-open")]
    DiamondWideOpen,
    [JsonStringEnumMemberName("diamond-wide-dot")]
    DiamondWideDot,
    [JsonStringEnumMemberName("diamond-wide-open-dot")]
    DiamondWideOpenDot,
    [JsonStringEnumMemberName("hourglass")]
    Hourglass,
    [JsonStringEnumMemberName("hourglass-open")]
    HourglassOpen,
    [JsonStringEnumMemberName("bowtie")]
    Bowtie,
    [JsonStringEnumMemberName("bowtie-open")]
    BowtieOpen,
    [JsonStringEnumMemberName("circle-cross")]
    CircleCross,
    [JsonStringEnumMemberName("circle-cross-open")]
    CircleCrossOpen,
    [JsonStringEnumMemberName("circle-x")]
    CircleX,
    [JsonStringEnumMemberName("circle-x-open")]
    CircleXOpen,
    [JsonStringEnumMemberName("square-cross")]
    SquareCross,
    [JsonStringEnumMemberName("square-cross-open")]
    SquareCrossOpen,
    [JsonStringEnumMemberName("square-x")]
    SquareX,
    [JsonStringEnumMemberName("square-x-open")]
    SquareXOpen,
    [JsonStringEnumMemberName("diamond-cross")]
    DiamondCross,
    [JsonStringEnumMemberName("diamond-cross-open")]
    DiamondCrossOpen,
    [JsonStringEnumMemberName("diamond-x")]
    DiamondX,
    [JsonStringEnumMemberName("diamond-x-open")]
    DiamondXOpen,
    [JsonStringEnumMemberName("cross-thin")]
    CrossThin,
    [JsonStringEnumMemberName("cross-thin-open")]
    CrossThinOpen,
    [JsonStringEnumMemberName("x-thin")]
    XThin,
    [JsonStringEnumMemberName("x-thin-open")]
    XThinOpen,
    [JsonStringEnumMemberName("asterisk")]
    Asterisk,
    [JsonStringEnumMemberName("asterisk-open")]
    AsteriskOpen,
    [JsonStringEnumMemberName("hash")]
    Hash,
    [JsonStringEnumMemberName("hash-open")]
    HashOpen,
    [JsonStringEnumMemberName("hash-dot")]
    HashDot,
    [JsonStringEnumMemberName("hash-open-dot")]
    HashOpenDot,
    [JsonStringEnumMemberName("y-up")]
    YUp,
    [JsonStringEnumMemberName("y-up-open")]
    YUpOpen,
    [JsonStringEnumMemberName("y-down")]
    YDown,
    [JsonStringEnumMemberName("y-down-open")]
    YDownOpen,
    [JsonStringEnumMemberName("y-left")]
    YLeft,
    [JsonStringEnumMemberName("y-left-open")]
    YLeftOpen,
    [JsonStringEnumMemberName("y-right")]
    YRight,
    [JsonStringEnumMemberName("y-right-open")]
    YRightOpen,
    [JsonStringEnumMemberName("line-east-west")]
    LineEastWest,
    [JsonStringEnumMemberName("line-east-west-open")]
    LineEastWestOpen,
    [JsonStringEnumMemberName("line-north-south")]
    LineNorthSouth,
    [JsonStringEnumMemberName("line-north-south-open")]
    LineNorthSouthOpen,
    [JsonStringEnumMemberName("line-northeast")]
    LineNorthEast,
    [JsonStringEnumMemberName("line-northeast-open")]
    LineNorthEastOpen,
    [JsonStringEnumMemberName("line-northwest")]
    LineNorthWest,
    [JsonStringEnumMemberName("line-northwest-open")]
    LineNorthWestOpen,
    [JsonStringEnumMemberName("arrow-up")]
    ArrowUp,
    [JsonStringEnumMemberName("arrow-up-open")]
    ArrowUpOpen,
    [JsonStringEnumMemberName("arrow-down")]
    ArrowDown,
    [JsonStringEnumMemberName("arrow-down-open")]
    ArrowDownOpen,
    [JsonStringEnumMemberName("arrow-left")]
    ArrowLeft,
    [JsonStringEnumMemberName("arrow-left-open")]
    ArrowLeftOpen,
    [JsonStringEnumMemberName("arrow-right")]
    ArrowRight,
    [JsonStringEnumMemberName("arrow-right-open")]
    ArrowRightOpen,
    [JsonStringEnumMemberName("arrow-bar-up")]
    ArrowBarUp,
    [JsonStringEnumMemberName("arrow-bar-up-open")]
    ArrowBarUpOpen,
    [JsonStringEnumMemberName("arrow-bar-down")]
    ArrowBarDown,
    [JsonStringEnumMemberName("arrow-bar-down-open")]
    ArrowBarDownOpen,
    [JsonStringEnumMemberName("arrow-bar-left")]
    ArrowBarLeft,
    [JsonStringEnumMemberName("arrow-bar-left-open")]
    ArrowBarLeftOpen,
    [JsonStringEnumMemberName("arrow-bar-right")]
    ArrowBarRight,
    [JsonStringEnumMemberName("arrow-bar-right-open")]
    ArrowBarRightOpen,
    [JsonStringEnumMemberName("arrow")]
    Arrow,
    [JsonStringEnumMemberName("arrow-open")]
    ArrowOpen,
    [JsonStringEnumMemberName("arrow-wide")]
    ArrowWide,
    [JsonStringEnumMemberName("arrow-wide-open")]
    ArrowWideOpen
}
